[workspace]
authors = ["Abdoul Tall <atall@eoas.ubc.ca>"]
channels = ["conda-forge", "nodefaults"]
name = "analysis-abdoul-314"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
arrow = "*"
bottleneck = "*"
cartopy = "*"
cliff = "*"
cmocean = "*"
coverage = "*"
dask = "*"
f90nml = "*"
gsw = "*"
ipdb = "*"
ipython = "*"
jupyterlab = "*"
lxml = "*"
matplotlib = "*"
nbsphinx = "*"
netcdf4 = "*"
numpy = "*"
openpyxl = "*"
pandas = "*"
pillow = "*"
pip = "*"
pyproj = "*"
pytest = "*"
python = "3.*"
pytz = "*"
python-dateutil = "*"
pyyaml = "*"
requests = "*"
retrying = "*"
scipy = "*"
shapely = "*"
sphinx = "*"
sphinx_rtd_theme = "*"
tqdm = "*"
xarray = "*"

[pypi-dependencies]
angles = "*"
salishseatools = { git = "https://github.com/SalishSeaCast/tools.git", subdirectory = "SalishSeaTools" }
